// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type CategoryTableRow = {
    id: string;
    name: string;
    description: string;
    todo: { nodes: TodoTableRow[] };
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    password: string;
  };

  type TodoTableRow = {
    id: string;
    name: string;
    description: string;
    done: boolean;
    category: CategoryTableRow;
    attachment: string;
  };

  type AllCategoryViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
    };
    write: {
      email: string;
      password: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllTasksViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      done: boolean;
      category: CategoryTableRow;
      attachment: string;
    };
    write: {
      name: string;
      description: string;
      done: boolean;
      category: string[];
      attachment: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type CollaboratorsViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
    };
    write: {
      email: string;
      password: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    allCategory: AllCategoryViewRow;
    allMember: AllMemberViewRow;
    allTasks: AllTasksViewRow;
    collaborators: CollaboratorsViewRow;
  };
}
