name: Release Doc

on:
  push:
    paths:
      - "doc/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v1
        with:
          image: docker:latest
          run: |
            cd doc
            sh ./build.sh
            [[ ! -d build ]] && echo 'Build failed' && exit 1
      - uses: actions/setup-node@v2
      - run: cd doc && npx vercel --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
