name: Test CLI
on:
  push:
    paths:
      - "packages/cli/**"
jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn
          yarn lerna bootstrap
          yarn lerna run build
          cd packages/cli
          yarn
          yarn test
