name: Test React
on:
  push:
    paths:
      - "packages/react/**"
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          cd packages/react
          yarn
          yarn test
