name: Test React
on:
  push:
    paths:
      - "packages/react/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn
          yarn lerna run build
          yarn lerna bootstrap
          cd packages/react
          yarn
          yarn test
