name: Test CLI
on:
  [push]
  # push:
  #   paths:
  #     - "packages/cli/**"
  #   branches:
  #     - main
jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          cd packages/cli
          yarn
          yarn test
