name: Test SDK
on:
  push:
    paths:
      - "packages/sdk/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn
          yarn lerna bootstrap
          yarn lerna run build
          cd packages/sdk
          yarn
          yarn tsc --noEmit
