name: Test Client
on:
  push:
    paths:
      - "packages/client/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn
          yarn lerna bootstrap --npm-client yarn
          yarn lerna run build
          cd packages/client
          yarn test
